steps:
  - label: "Benchmarks"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
    env:
      CODESPEED_PROJECT: "$BUILDKITE_PIPELINE_NAME"
      CODESPEED_BRANCH: "$BUILDKITE_BRANCH"
      CODESPEED_COMMIT: "$BUILDKITE_COMMIT"
      CODESPEED_EXECUTABLE: "Julia 1.6"
    command: |
      julia --project -e '
        ENV["CODESPEED_ENVIRONMENT"] = ENV["BUILDKITE_AGENT_NAME"]
        println("Preparing Environment")
        using Pkg
        # push!(LOAD_PATH, @__DIR__)
        # Pkg.activate()
        # pkg"add Flux#$(BUILDKITE_COMMIT)"
        Pkg.instantiate()
        println("Starting Benchmarks")
        using FluxBench
        FluxBench.submit()'
    agents:
      queue: "benchmark"
      cuda: "*"
