steps:
  - label: "Benchmarks"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
    env:
      CODESPEED_PROJECT: "FluxBench"
      CODESPEED_BRANCH: "$BUILDKITE_BRANCH"
      CODESPEED_COMMIT: "$BUILDKITE_COMMIT"
      CODESPEED_EXECUTABLE: "Julia 1.6"
      CODESPEED_SERVER: "https://speed.fluxml.ai"
    command: |
      julia --project -e '
        ENV["CODESPEED_ENVIRONMENT"] = "FluxBench" # ENV["BUILDKITE_AGENT_NAME"]
        println("Preparing Environment")
        using Pkg
        Pkg.instantiate()
        println("Starting Benchmarks")
        using FluxBench
        FluxBench.submit()'
    agents:
      queue: "benchmark"
      cuda: "*"
